version: '3.4'

services:
  task_1_cbow: &task
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./exp1:/workdir/exp1
      - ./exp2:/workdir/exp2
      - ./data:/workdir/data
    environment: 
     - CONFNAME=task_1_cbow
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
  task_1_bert:
    <<: *task
    environment: 
     - CONFNAME=task_1_bert
  task_1_roberta:
    <<: *task
    environment: 
     - CONFNAME=task_1_roberta
  task_2_cbow:
    <<: *task
    environment: 
     - CONFNAME=task_2_cbow
  task_2_bert:
    <<: *task
    environment: 
     - CONFNAME=task_2_bert
  task_2_roberta:
    <<: *task
    environment: 
     - CONFNAME=task_2_roberta
